# Generated by Django 3.2.8 on 2021-11-03 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataafterparsing',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
