# Generated by Django 3.2.8 on 2021-10-31 06:34

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20211030_1236'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='databeforeparsing',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
