# Generated by Django 3.2.8 on 2021-10-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_databeforeparsing_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='databeforeparsing',
            managers=[
            ],
        ),
    ]
