# Generated by Django 3.2.8 on 2021-11-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_databeforeparsing_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataafterparsing',
            name='site_name',
        ),
        migrations.AddField(
            model_name='dataafterparsing',
            name='site_connect',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataafterparsing',
            name='content_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dataafterparsing',
            name='main_heading',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dataafterparsing',
            name='site_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='databeforeparsing',
            name='hours_shift',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='databeforeparsing',
            name='minutes_shift',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='databeforeparsing',
            name='seconds_shift',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='databeforeparsing',
            name='site_name',
            field=models.CharField(max_length=50),
        ),
    ]
