# Generated by Django 3.2.8 on 2021-11-03 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20211103_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataafterparsing',
            name='date_create',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
